services:
  app:
    build:
      context: ./containers/laravel
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./containers/laravel/:/var/www/html
      - storage:/var/www/html/storage
      - logs:/var/www/html/storage/logs
      - cache:/var/www/html/bootstrap/cache
    environment:
      - TZ=Asia/Tokyo
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravelpassword
      - SESSION_DRIVER=database
    depends_on:
      - db
    command: >
      sh -c "
      php artisan key:generate --no-interaction || true &&
      php artisan config:cache &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build: 
      context: .
      dockerfile: containers/nginx/Dockerfile
    command: >
      /bin/bash -c
      "envsubst '$$NGINX_SERVER_NAME $$NGINX_SERVER_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    environment:
      - TZ=Asia/Tokyo
      - NGINX_SERVER_NAME=localhost
      - NGINX_SERVER_PORT=80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - tmp:/app/tmp
      - public:/app/public
    depends_on:
      - app

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped

  playwright:
    build:
      context: .
      dockerfile: ./containers/playwright/Dockerfile
    container_name: playwright
    volumes:
      - ./containers/laravel/:/var/www/html
      - ./containers/playwright/e2e:/var/www/html/tests/e2e
    ports:
      - "9323:9323"
    tty: true
    depends_on:
      - nginx

volumes:
  postgres_data:
  tmp:
  public:
  logs:
  cache:
  storage: